pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install -Denforcer.skip=true'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn -Denforcer.skip=true test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        
        stage('Complete'){
            steps{
               echo "Job Complete!"
            }
        }
    }
}
